Frontend/k-rangers-frontend/docs/rule.md
Frontend/k-rangers-frontend/src/App.js
Frontend/k-rangers-frontend/src/index.js
Frontend/k-rangers-frontend/src/page/test.jsx

chore: Front Router 세팅

---

Backend/.gitignore
Backend/src/main/resources/application-local.yml
Backend/src/main/resources/application-prod.yml
Backend/src/main/resources/application.yml
Backend/src/main/resources/template-application-local.yml

- [o] 🔧 기타 (Chore)
프로젝트의 안정성과 보안을 강화하기 위해, 환경별(local, prod) 설정을 분리하고 민감한 정보가 Git에 커밋되지 않도록 구성했습니다.
- `application.yml`: 모든 환경에서 사용될 공통 설정을 정의합니다.
- `application-local.yml`: 로컬 개발 환경을 위한 설정을 정의합니다. (DB, API 키 등)
- `application-prod.yml`: 운영 환경을 위한 설정을 정의합니다.
- `template-application-local.yml`: 새로운 팀원이 로컬 설정을 쉽게 구성할 수 있도록 템플릿을 제공합니다.
- `.gitignore`: `application-local.yml`, `application-prod.yml` 등 민감한 정보가 포함된 파일을 Git 추적에서 제외하여 보안을 강화합니다.
- [o] 코드가 정상적으로 빌드됨
- [o] 기본 기능이 정상 동작함
- [o] 다른 기능에 영향을 주지 않음
- [o] 필요없는 주석 및 코드 삭제했는가

chore: 환경별 설정 분리 및 .gitignore 구성

---

Frontend/k-rangers-frontend/src/components/AccessChips.jsx
Frontend/k-rangers-frontend/src/css/AccessChips.module.css
Frontend/k-rangers-frontend/src/page/MainPage.jsx

맞춤혀 관광지 찾기 리스트 컴포넌트 구현
Closes #15

feat: 맞춤형 관광지 찾기 컴포넌트 생성

---

Frontend/k-rangers-frontend/src/components/RecommendedCard.jsx
Frontend/k-rangers-frontend/src/components/RecommendedList.jsx
Frontend/k-rangers-frontend/src/css/AccessChips.module.css
Frontend/k-rangers-frontend/src/css/RecommendedCard.module.css
Frontend/k-rangers-frontend/src/css/RecommendedList.module.css
Frontend/k-rangers-frontend/src/page/MainPage.jsx

추천여행지에 대한 카드리스트 기본 틀 구현
Closes #20

feat: 추천 여행지 컴포넌트 생성

---

Frontend/k-rangers-frontend/package-lock.json
Frontend/k-rangers-frontend/package.json
Frontend/k-rangers-frontend/src/App.js
Frontend/k-rangers-frontend/src/components/BottomNav.jsx
Frontend/k-rangers-frontend/src/css/BottomNav.module.css
Frontend/k-rangers-frontend/src/css/MainPage.module.css
Frontend/k-rangers-frontend/src/page/MainPage.jsx

feat: 네비게이션 바 컴포넌트 생성

---

Frontend/k-rangers-frontend/src/components/BottomNav.jsx
Frontend/k-rangers-frontend/src/css/BottomNav.module.css

네비게이션 바에서 찜 목록, save.jsx 삭제와 .gitignore 파일 업데이트
Closes #37 
Relates to #35

refactor: 네비게이션 컴포넌트 구조 변경

---

Backend/.dockerignore
Backend/.github/workflows/deploy.yml
Backend/.github/workflows/fly-deploy.yml
Backend/Dockerfile
Backend/build.gradle
Backend/fly.toml
Backend/src/main/java/org/kmr/backend/config/SecurityConfig.java
Backend/src/main/resources/application-local.yml
Backend/src/main/resources/application.properties
Backend/src/main/resources/application.yml

프론트엔드가 최신 버전의 API 명세서(Swagger UI)에 접근할 수 있도록 하는 기능추가
Closes #38

[feat] add-swagger-ui

---

Backend/src/main/java/org/kmr/backend/security/SecurityConfig.java

보안 설정의 문제로 Swagger 동작이 되지 않는 부분 작업
Closes #54

[chore] refine-security-rules

---

Frontend/k-rangers-frontend/.gitignore
Frontend/k-rangers-frontend/src/components/Map.jsx
Frontend/k-rangers-frontend/src/config/env.js

refactor: api키 재발급 및 .env.local 파일로 이동

---

Frontend/k-rangers-frontend/src/components/Map.jsx

bug: 빌드 의존성 배열 오류 수정

---

Frontend/k-rangers-frontend/src/App.css

pwa 뷰포트 오류 확인

---

Frontend/k-rangers-frontend/src/index.css

design: ios 상단 노치 여백수정

---

Frontend/k-rangers-frontend/src/App.css
Frontend/k-rangers-frontend/src/css/BottomNav.module.css
Frontend/k-rangers-frontend/src/css/BottomSheet.module.css
Frontend/k-rangers-frontend/src/css/MainPage.module.css
Frontend/k-rangers-frontend/src/css/MapPage.module.css
Frontend/k-rangers-frontend/src/page/MapPage.jsx

Bottom Nav 디자인 수정 및 불필요한 코드 삭제
Closes #78 
이미지 변경사항 없음

Design : Bottom Nav 디자인 수정 및 불필요한 코드 삭제

---

Frontend/k-rangers-frontend/src/css/BottomNav.module.css
Frontend/k-rangers-frontend/src/css/BottomSheet.module.css

BottomSheet Position 수정
Closes #82

Design: BottomSheet Position 수정

---

.github/workflows/serverdeploy.yml

Add GitHub Actions workflow for server deployment

---

Frontend/k-rangers-frontend/src/css/BottomNav.module.css

[design] 네비게이션 바 높이 조정

---

.github/workflows/serverdeploy.yml

Add environment file to Docker run command

---

Backend/src/main/resources/application-prod.yml
Backend/src/main/resources/application.yml

[chore] application.yml

---

Backend/src/main/java/org/kmr/backend/config/SwaggerConfig.java

[feat] SwaggerConfig

---

Backend/src/main/resources/application.yml

[refactor] application.yml

---

Frontend/k-rangers-frontend/src/App.js
Frontend/k-rangers-frontend/src/components/BottomNav.jsx
Frontend/k-rangers-frontend/src/css/Login.module.css
Frontend/k-rangers-frontend/src/page/LoginPage.jsx
Frontend/k-rangers-frontend/src/page/MyPage.jsx

로그인 페이지 생성

---

.idea/gradle.xml
Backend/src/main/java/org/kmr/backend/accommodation/domain/Accommodation.java
Backend/src/main/java/org/kmr/backend/accommodation/dto/response/AccommodationResponse.java
Backend/src/main/java/org/kmr/backend/attraction/domain/Attraction.java
Backend/src/main/java/org/kmr/backend/attraction/dto/response/AttractionResponse.java
Backend/src/main/java/org/kmr/backend/config/DataLoader.java

attraction, accommodation 조회할 때 imageUrl 반환 추가
Closes #156

feat: imageUrl add

---

.idea/misc.xml
.idea/modules/backend.main.iml
Backend/src/main/java/org/kmr/backend/review/api/ReviewController.java
Backend/src/main/java/org/kmr/backend/review/dto/MyReviewsResponseDTO.java
Backend/src/main/java/org/kmr/backend/review/repository/ReviewRepository.java
Backend/src/main/java/org/kmr/backend/review/service/ReviewService.java

사용자가 쓴 리뷰 전체(attractions, accommodations) 조회
Closes #166

feat: 사용자가 쓴 review 모두 조회

---

Backend/.gitignore
Backend/src/main/resources/application.yml

[fix] server

---

Backend/src/main/resources/application.yml

[fix] serverrrr

---

Frontend/k-rangers-frontend/src/config/env.js
Frontend/k-rangers-frontend/src/hooks/useAttraction.jsx

useAttraction.jsx 내부 `use` import 삭제
Closes #185

Bug: Netlify 빌드 중 ESLint 에러 수정

---

Backend/src/main/resources/application.yml

[fix] application.yml

---

Backend/src/main/java/org/kmr/backend/config/SwaggerConfig.java

[fix] swagger

---

Backend/src/main/java/org/kmr/backend/config/SwaggerConfig.java

[refactor] SwaggerConfig
